dpi: 300  # Enhanced DPI for improved OCR accuracy
language: 'ara'  # Add multiple languages
tesseract_config: '--psm 3 --oem 3'
header_margin: 80
footer_margin: 80
openai_api_key: ''

# String similarity conf
thresholds:
  levenstein: 0.8
  cosine: 0.85
  ngrams: 0.75
  jaccard: 0.7
  damerau_levenshtein: 0.78

hyperparameters:
  ngrams_n: 3  # N for N-grams
  max_distance: 100